I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 107, in script
    evelyn "Pleased to meet you %(player_fname)! We're now all set to begin the interview."
ValueError: unsupported format character '!' (0x21) at index 35

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 107, in script
    evelyn "Pleased to meet you %(player_fname)! We're now all set to begin the interview."
  File "renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1408, in say
    what = what % tag_quoting_dict
ValueError: unsupported format character '!' (0x21) at index 35

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Orbital Weapons Dating Simulator 1.0
Sat Dec 25 22:11:35 2021
